name: Build
on:
  workflow_run:
    workflows: ["Run Tests"]
    branches: [main]
    types: 
      - completed
env:
  CARGO_TERM_COLOR: always
jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install cargo bundle
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-bundle
    - name: Build bundle
      uses: actions-rs/cargo@v1
      with:
        command: bundle
        args: --release
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: icy_term_linux
        path: target/release/bundle/deb/icy_term_*.deb
  build_osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build bundle
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: icy_term_osx
        path: target/release/icy_term_osx
  
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build bundle
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: icy_term_windows
        path: target/release/icy_term_windows.exe
